<?/*

  Last update: 2015-03-13

  A collection of domain names used by disposable / temporary email providers.
  Useful if you want to block a big part of fake registrations on a website.

  Remember that this list will never be complete, and that black listing in
  this way is only a tool, not a complete solution.

  Collection made by Johannes Lundberg
  Send updates to first.last@gmail.com

  Released to the public domain.

*/

$temporaryEmailProviders = array(
"emailgo.de"=>1,
"mbx.cc"=>1,
"spamgourmet.com"=>1,
"deadaddress.com"=>1,
"keepmymail.com"=>1,
"12minutemail.com"=>1,
"10x9.com"=>1,
"trashinbox.com"=>1,
"hmamail.com"=>1,
"spamkill.info"=>1,
"yxzx.net"=>1,
"yopmail.com"=>1,
"dontsendmespam.de"=>1,
"spamavert.com"=>1,
"mailinator.com"=>1,
"no-spam.ws"=>1,
"nobugmail.com"=>1,
"losemymail.com"=>1,
"nabuma.com"=>1,
"nobuma.com"=>1,
"bugmenever.com"=>1,
"ignoremail.com"=>1,
"10minutemail.com"=>1,
"pookmail.com"=>1,
"humaility.com"=>1,
"incognitomail.org"=>1,
"mail4trash.com"=>1,
"spaml.de"=>1,
"dodgit.com"=>1,
"filzmail.com"=>1,
"spaml.com"=>1,
"eyepaste.com"=>1,
"pjjkp.com"=>1,
"odnorazovoe.ru"=>1,
"wwwnew.eu"=>1,
"example.com"=>1,
"bofthew.com"=>1,
"lhsdv.com"=>1,
"prtnx.com"=>1,
"despam.it"=>1,
"lawlita.com"=>1,
"oneoffmail.com"=>1,
"spamgourmet.com"=>1,
"mytrashmail.com"=>1,
"2prong.com"=>1,
"temporaryinbox.com"=>1,
"jetable.org"=>1,
"tempinbox.com"=>1,
"guerrillamail.com"=>1,
"dontreg.com"=>1,
"bugmenot.com"=>1,
"wh4f.org"=>1,
"spamhole.com"=>1,
"tempomail.fr"=>1,
"spammotel.com"=>1,
"spambox.us"=>1,
"tempemail.net"=>1,
"mailscrap.com"=>1,
"maileater.com"=>1,
"spam.la"=>1,
"fakedemail.com"=>1,
"spam.su"=>1,
"antireg.ru"=>1,
"mailforspam.com"=>1,
"asdasd.ru"=>1,
"slopsbox.com"=>1,
"tilien.com"=>1,
"trashmail.net"=>1,
"otherinbox.com"=>1,
"antireg.com"=>1,
"mailinator2.com"=>1,
"sogetthis.com"=>1,
"mailin8r.com"=>1,
"mailinator.net"=>1,
"spamherelots.com"=>1,
"baxomale.ht.cx"=>1,
"thisisnotmyrealemail.com"=>1,
"spambog.com"=>1,
"bsnow.net"=>1,
"trash-mail.com"=>1,
"jetable.org"=>1,
"jetable.net"=>1,
"mailexpire.com"=>1,
"garrifulio.mailexpire.com"=>1,
"sofort-mail.de"=>1,
"uggsrock.com"=>1,
"nurfuerspam.de"=>1,
"binkmail.com"=>1,
"mailcatch.com"=>1,
"guerrillamailblock.com"=>1,
"cust.in"=>1,
"meltmail.com"=>1,
"wegwerfemail.de"=>1,
"giantmail.de"=>1,
"zippymail.info"=>1,
"rmqkr.net"=>1,
"mohmal.com"=>1,
"teleworm.us"=>1,
"fakeinbox.com"=>1,
"armyspy.com"=>1,
"dayrep.com"=>1,
"trbvm.com"=>1,
"ce.mintemail.com"=>1,
"sharklasers.com"=>1,
"guerillamail.org"=>1,
"mailnull.com"=>1,
"grr.la"=>1,
"spam4.me"=>1,
"guerrillamail.net"=>1,
"guerrillamail.de"=>1,
"guerrillamail.biz"=>1,
);

?>
